name: Selenium Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Detected Chrome version: $CHROME_VERSION"
          sudo apt install -y chromium-chromedriver
          which chromedriver

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Selenium Test
        run: python Futurx.py
