name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Chrome
      uses: actions/setup-chrome@v2
      with:
        chrome-version: 'latest'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python your_test_script.py
