name: Selenium Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Use windows-latest if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version  # Verify installation

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip
          chromedriver --version  # Verify installation

      - name: Run Selenium Tests
        run: python Futurx.py
