name: Selenium Test with Chrome

on:
  push:
    branches:
      - master

jobs:
  selenium:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome
      uses: actions/setup-chrome@v2
      with:
        chrome-version: 'latest'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies like selenium

    - name: Run tests
      run: |
        python your_test_script.py  # Run your test script here
